### ISSUE TITLE
Add support for datetime.date and datetime.datetime parsers

### ISSUE THREAD

**Issue by neelmraman** [anntzer/defopt#113]
Nearly all of my CLIs require a date argument (e.g., a run date or begin and end dates), and I've found that I'm having to repeat a custom date parser over and over again. Would it make sense for defopt to natively support date/datetime parsing? Perhaps this could just delegate to dateutil's `parser.parse`, and if that doesn't parse a datetime string the way one would expect, they could still specify their own parser with a working format string.

**Comment by anntzer** [comment]
Can you clarify what you are looking for?  Is it simply so that you don't have to write `defopt.run(..., parsers={datetime.datetime: dateutil.parser.parse})`?  I would be rather opposed to adding a dependency on dateutil, and trying to import it (ignoring the import error if it is not present) would slow down the defopt import time (something I would like to keep under control, as in https://github.com/anntzer/defopt/pull/97#issuecomment-998216209) and perhaps be a source of not so nice variations in behavior depending on the current python environment.

I also note that there are quite a few different options to dateutil.parser.parse so registering a default parser would only work for the default case anyways (if they want to set any of `default`, `ignoretz`, `tzinfos`, etc. they'll have to fall back to having their own parser -- which, as a side note, can be defined inline using `parsers={datetime.datetime: functools.partial(dateutil.parser.parse, default=...)}`).

**Comment by neelmraman** [comment]
Yup, specifically I've found that I've had to repeat something like `defopt.run(..., parsers={datetime.date: lambda arg: datetime.datetime.strptime(arg, "%Y%m%d").date())}` many times. But ah yeah the import time of dateutil may be prohibitive. I was just thinking it would be nice to support date/datetime parsing with minimal setup since other arg parsing libraries (like click, for example) can do this, but yeah perhaps there isn't a good way to do this in defopt for the reasons you provided.

**Comment by anntzer** [comment]
As you note yourself you need some non-trivial customization (e.g. in your case you specify a strptime format), which is not really something defopt can pick for you.  Also note that for compat with defopt you'd need to stuff that info into a type hint, which I guess would at best look like
```python
def foo(dt: mydatetime("%Y%m%d")): ...  # or with square brackets
```
which is probably not something static type checkers really like.  Actually, I personally don't care much about such type checkers so I'd probably(?) just write something like
```python
def mydatetime(fmt):
    def parse_date(s: str): return datetime.strptime(s, fmt)
    return parse_date
```
and put that into a helper module that I can reimport across my projects.

**Comment by neelmraman** [comment]
Oh yeah my current approach with the lambda function for parsing a date works fine with defopt and static type checkers (and for my use case at least, I would be fine giving up the customization for a more general datetime parsing solution). I wonder though if it would make sense to add a `date_formats` or `datetime_formats` parameter to `defopt.run` that takes a sequence of format strings to try in order (or perhaps even a mapping from parameter to a sequence of format strings). This would make the API but a bit more complicated, but would allow for more convenient date/datetime parsing and without defopt needing to import something else outside of the standard library.
