### ISSUE TITLE
Requestion: add an option to convert underscores to hyphens for all arguments

### ISSUE THREAD

**Issue by iskandr** [anntzer/defopt#124]
There's a confusing asymmetry between position and kwarg-only arguments in defopt: 

>Python positional-or-keyword parameters are converted to CLI positional arguments, with their name unmodified [[2]](https://github.com/anntzer/defopt/blob/66edf8d316006b5f9dd06bba816e19adec4210f1/doc/source/features.rst#id4). Python keyword-only parameters are converted to CLI flags, with underscores replaced by hyphens. Additionally, one-letter short flags are generated for all flags that do not share their initial with other flags.

Would it be possible to at least add an option to convert underscores in all argument names to hypens? Or, if @anntzer, you don't have time for that, would you be open to a PR that does this?

**Comment by anntzer** [comment]
I clarified the docs to show the actual behavior:
```
usage: test.py [-h] --kwonly-no-default KWONLY_NO_DEFAULT [--kwonly-with-default KWONLY_WITH_DEFAULT]
               positional_no_default [positional_with_default]

positional arguments:
  positional_no_default
  positional_with_default
                        (default: some_value)

options:
  -h, --help            show this help message and exit
  --kwonly-no-default KWONLY_NO_DEFAULT
  --kwonly-with-default KWONLY_WITH_DEFAULT
                        (default: some_value)
```
basically the flags themselves use dashes, but the values use underscores.

I'm not sure what is the standard, if any, but from a quick look, the man page of ls (https://manpages.ubuntu.com/manpages/focal/man1/ls.1.html) documents `--time-style=TIME_STYLE` so that seems consistent to me?  But I would be willing to reconsider if you can point me to (standard-ish) pages which do the opposite.

**Comment by iskandr** [comment]
Gotcha, sorry I misunderstood. 

This pretty much does what I want then!
