### ISSUE TITLE
function name aliases?

### ISSUE THREAD

**Issue by johnfarina** [anntzer/defopt#63]
Basically the only thing that I miss from click, argh, clize, and other cli frameworks is the ability to rename and/or alias function names with friendlier cli names. Alas, those competitors are otherwise far more annoying to use than defopt.

Specifically, it would be great to have functionality like [this](https://argh.readthedocs.io/en/latest/reference.html#argh.decorators.named), or how clize accepts a dict of {cli_name:original_function_name} pairs, available in defopt.

Are there any plans to implement something similar?

(Full disclosure: I haven't looked through defopt's code enough to know how hard it might be to do so)

**Comment by evanunderscore** [comment]
Thanks for the report. I have no plans to implement this myself, but would happily take a PR if you or someone else would like to do it.

It should be relatively easy to alter the subcommand names; you can see where defopt sets the name of the subcommand [here](https://github.com/evanunderscore/defopt/blob/cb5ef0d75022122e12884caf9624e48d5f180553/defopt.py#L135). Aliases might be a little harder since I don't believe argparse supports alises for subcommands out of the box. You might have to look at how argh/clize work for inspiration.

**Comment by anntzer** [comment]
> I don't believe argparse supports alises for subcommands out of the box.

It does (via the not so well documented `aliases` argument to add_parser(), https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers), although it's Py3 only I think.

**Comment by johnfarina** [comment]
Thanks for the pointer into the code! Now that I've had a look, it's actually easy to implement clize-style function renaming by passing a dict to `defopt.run`. I'll submit a PR once I update the documentation on my fork and figure out how to add unittests :)

I'm less interested in assigning multiple aliases to a given function.

**Comment by anntzer** [comment]
Implemented in https://github.com/anntzer/defopt/commit/176cd559042f02ba98ccb5a12edc86476df278b5.
